version: '3.9'

networks:
  loki:

services:
  loki:
    container_name: loki
    image: grafana/loki:2.4.1
    ports:
      - 3100:3100
    volumes:
      - $PWD/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki


  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.1
    volumes:
      - /var/log:/var/log
      - $PWD/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki


  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - loki
