{
 "title": "Nginx Log",
 "tags": [
  "Nginx",
  "Log",
  "JSON"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label Name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({$label_name=~\"$label_value\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({$label_name=~\"$label_value\"}, instance)"
   },
   { "name": "server_name", "label": "Server Name", "query": ".*" },
   { "name": "uri", "label": "Uri", "query": ".*" },
   { "name": "request_uri", "label": "Request Uri", "query": ".*" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Key results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "NGINX logs in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} [$__interval])",
     "legendFormat": "$label_value"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Total visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr, remote_port) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "NGINX log lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} [$__interval])"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | status >= 500 | __error__=\"\" [$__interval])) / (sum(count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Bingbot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |= \"bingbot\")[$__interval])) / (sum(count_over_time(({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} != \"bingbot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" | line_format \"➡️ {{.request_method}} {{.request_uri}} [status={{.status}}, http_host={{.http_host}}, remote_addr={{.remote_addr}}, request_time={{.request_time}}] \""
    }
   ]
  },
  {
   "title": "Request statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "PV and UV",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(host) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval]))",
       "legendFormat": "PV"
      },
      {
       "expr": "count(sum by (remote_addr, remote_port) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "UV"
      }
     ]
    },
    {
     "title": " Request Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile_over_time(0.50,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap request_time |  __error__ = \"\"  [$__interval]) by (host)",
       "legendFormat": "pct50"
      },
      {
       "expr": "quantile_over_time(0.90,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap request_time |  __error__ = \"\"  [$__interval]) by (host)",
       "legendFormat": "pct90"
      },
      {
       "expr": "quantile_over_time(0.95,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap request_time |  __error__ = \"\"  [$__interval]) by (host)",
       "legendFormat": "pct95"
      },
      {
       "expr": "quantile_over_time(0.99,{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap request_time |  __error__ = \"\"  [$__interval]) by (host)",
       "legendFormat": "pct99"
      },
      {
       "expr": "max by (host) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | unwrap request_time |  __error__ = \"\"  [$__interval]))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "HTTP status codes over time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | status=200 | unwrap bytes_sent |  __error__ = \"\" [$__interval]))",
       "legendFormat": "Bytes sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 100 Requested Pages By Request Uri",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(100, sum by (request_uri) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Requested Pages By Uri",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "topk(100, sum by (uri) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Request Time By Request Uri",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "topk(100, max by (request_uri) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" | unwrap request_time [$__interval])))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Request Time By Uri",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "topk(100, max by (uri) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" | unwrap request_time [$__interval])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Bytes Sent By Request Uri",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "topk(100, max by (request_uri) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" | unwrap bytes_sent  [$__interval])))",
       "legendFormat": "{{request_uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Bytes Sent By Uri",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "topk(100, max by (uri) (max_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\"  | status = 200 and request_uri != \"/\" | __error__ = \"\" | unwrap bytes_sent [$__interval])))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Top 100 Server Name",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "topk(100, sum by (server_name) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | server_name != \"\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{server_name}}"
      }
     ]
    },
    {
     "title": "Top 100 HTTP X Forwarded For",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "topk(100, sum by (http_x_forwarded_for) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | http_x_forwarded_for != \"\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{http_x_forwarded_for}}"
      }
     ]
    },
    {
     "title": "Top 100 HTTP Referers",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "topk(100, sum by (http_referer) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{http_referer}}"
      }
     ]
    },
    {
     "title": "Top 100 User Agents",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "topk(100, sum by (http_user_agent) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" |  __error__ = \"\" [$__interval])))",
       "legendFormat": "{{http_user_agent}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Geographical information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 100 visitor IPs",
     "type": "table",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "topk(100, sum by (remote_addr, geoip2_country_code, geoip2_city_name) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top 100 Countries",
     "type": "table",
     "gridPos": { "h": 11, "w": 4, "x": 13, "y": 4 },
     "targets": [
      {
       "expr": "topk(100, sum by (geoip2_country_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | geoip2_country_code != \"\" |  __error__ = \"\" [$__interval])))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Top 100 Cities",
     "type": "table",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
     "targets": [
      {
       "expr": "topk(100, sum by (geoip2_country_code, geoip2_city_name) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | geoip2_city_name != \"\" | __error__ = \"\" [$__interval])))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Requests per Country",
     "type": "geomap",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by (geoip2_country_code) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json | server_name =~ \"$server_name\" | uri =~ \"$uri\" | request_url =~ \"$request_uri\" | geoip2_country_code != \"\" | __error__ = \"\" [$__interval]))",
       "legendFormat": "{{geoip2_country_code}}"
      }
     ]
    }
   ]
  }
 ]
}